services:
    nginx-gateway:
        build: ./nginx-gateway
        ports:
            - "3000:80"
        depends_on:
            auth-service-go:
                condition: service_started
            backend-java:
                condition: service_started
            # frontend-react:
            #     condition: service_started

    auth-service-go:
        build: ./auth-service-go
        expose:
            - "8081"
        environment:
            - REDIS_ADDR=redis:6379
            - ETCD_ENDPOINTS=etcd:2379
        depends_on:
            redis:
                condition: service_healthy

    backend-java:
        build: ./backend-java
        expose:
            - "8080"
        environment:
            - SPRING_DATASOURCE_URL
            - SPRING_DATASOURCE_USERNAME
            - SPRING_DATASOURCE_PASSWORD
            - SPRING_DATA_REDIS_HOST=redis
            - SPRING_RABBITMQ_USERNAME
            - SPRING_RABBITMQ_PASSWORD
            - SHOP_MINIO_ACCESS_KEY
            - SHOP_MINIO_SECRET_KEY

    frontend-react:
        build: ./frontend-react
        expose:
            - "80"
        depends_on:
            nginx-gateway:
                condition: service_started

    order-worker-python:
        build: ./order-worker-python
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
            - RABBITMQ_USER
            - RABBITMQ_PASSWORD

    postgres:
        image: postgres:18.3
        shm_size: 128mb
        expose:
            - "5432"
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
        volumes:
            - postgres-data:/var/lib/postgresql
            - ./infra/postgres-init/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
        
    redis:
        image: redis:8.6.1
        expose:
            - "6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5

    rabbitmq:
        image: rabbitmq:4.2.4
        expose:
            - "5672"
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS

    etcd:
        image: quay.io/coreos/etcd:v3.6.8
        expose:
            - "2379"
        environment:
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # hardcoded
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379 # hardcoded

    minio:
        image: minio/minio
        expose:
            - "9000"
        environment:
            - MINIO_ROOT_USER
            - MINIO_ROOT_PASSWORD
        volumes:
            - minio-data:/data
        command: server /data

    minio-init:
        image: minio/mc 
        environment:
            - MINIO_ROOT_USER
            - MINIO_ROOT_PASSWORD
        volumes:
            - ./infra/minio-init/init.sh:/init.sh
            - ./infra/generated-images/products:/seed/products
        links:
            - minio:minio
        entrypoint: /bin/sh
        command: /init.sh

volumes:
    postgres-data:
    minio-data:
